// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type LoginReq struct {
}

type LoginResp struct {
}

type RegisterReq struct {
	Phone    string `json:"phone"`    // 手机号
	Nickname string `json:"nickname"` // 呢称
	Username string `json:"username"` // 姓名
	Password string `json:"password"` // 密码
	Avatar   string `json:"avatar"`
	Gender   int64  `json:"gender"` // 姓别
}

type RegisterResp struct {
}

type UserInfoReq struct {
}

type UserInfoResp struct {
}
