// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package userclient

import (
	"context"

	"easy-chat/examples/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq  = user.CreateReq
	CreateResp = user.CreateResp
	UserReq    = user.UserReq
	UserResp   = user.UserResp

	User interface {
		// CreateUser 创建用户信息
		CreateUser(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		// GetUser  获取用户信息
		GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// CreateUser 创建用户信息
func (m *defaultUser) CreateUser(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

// GetUser  获取用户信息
func (m *defaultUser) GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
