// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package server

import (
	"context"

	"easy-chat/examples/user/rpc/internal/logic"
	"easy-chat/examples/user/rpc/internal/svc"
	"easy-chat/examples/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// CreateUser 创建用户信息
func (s *UserServer) CreateUser(ctx context.Context, in *user.CreateReq) (*user.CreateResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

// GetUser  获取用户信息
func (s *UserServer) GetUser(ctx context.Context, in *user.UserReq) (*user.UserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
