// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type UserReq struct {
	Id string `json:"id"`
}

type UserResp struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
